import "./globals.css";
import { Poppins } from "next/font/google";
import Navbar from "./Components/Navbar";


const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased`}
      >
        {/* header section  */}
        <header className="max-w-7xl mx-auto">
          <Navbar />
        </header>

        {/* main section  */}
        <main
          // className="max-w-7xl mx-auto"
        >
          {children}
        </main>

        {/* footer section  */}


      </body>
    </html>
  );
}
